name_length: 50
email_length: 250
password_min_length: 6
avatar_size: 80
checked: "1"
per_page: 1

default_from_email: "haumin1201@gmail.com"
address: "smtp.gmail.com"
port: 587
domain: "gmail.com"
authentication: "plain"
enable_auto: true
password_expire_time: 2
content_length: 140
size_ava_sm: 50
n_5: 5
img_rule: "image/jpeg,image/gif,image/png"
size_limit: 400

